"""add indexes and FK on activity and session tables"""

revision = "228ac4e0ebf5"
down_revision = "cfa8efad03ed"
branch_labels = None
depends_on = None


from alembic import op


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_user_id"), ["user_id"], unique=False
        )
        batch_op.create_foreign_key("fk_activity_user_id", "user", ["user_id"], ["id"])

    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_sessions_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_sessions_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_sessions_is_active"))

    with op.batch_alter_table("activity", schema=None) as batch_op:
        batch_op.drop_constraint("fk_activity_user_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_activity_user_id"))
        batch_op.drop_index(batch_op.f("ix_activity_created_at"))

    # ### end Alembic commands ###
